name: Build Momentum Firmware

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build Momentum firmware
        run: |
          # Momentum build flags
          BUILD_TYPE="DEBUG=0 COMPACT=1"

          ./fbt $BUILD_TYPE updater_package
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: momentum-fw
          path: dist/f7-*/**
